version: '3.1'

services:

  nifi:
    image: apache/nifi:1.12.1
    restart: always
    volumes: 
      - "./drivers/:/opt/drivers/"
      - "./data/:/data/"
    ports:
      - 8080:8080
    environment: 
      NIFI_JVM_HEAP_INIT: 1G
      NIFI_JVM_HEAP_MAX: 2G
  
  elasticsearch:
    image: elasticsearch:7.5.2
    ports: 
      - 9200:9200
    environment: 
      discovery.type: single-node
  
  kibana:
    image: kibana:7.5.2
    ports: 
      - 5601:5601